// Retargeting a Claude Code request to another model: make it look like the request Claude Code itself sends for
// that model family (docs/wire-format.md §5). This is the only code that changes a request body; it runs only when
// route mode deliberately applies a plan. Pure: bytes in, bytes out (or a reason why not), plus the list of fields
// it changed so every routed record can say exactly what was rewritten.
import type { Tier } from "../config.js";

/** How a model family takes reasoning settings, as observed in native Claude Code requests. */
type ThinkingStyle = "adaptive" | "budget";
const STYLE: Readonly<Record<Tier, ThinkingStyle>> = { haiku: "budget", sonnet: "adaptive", opus: "adaptive", fable: "adaptive" };
/** Families that accept `role:"system"` messages and `output_config.effort` (both rejected by Haiku 4.5: M1 experiment). */
const ACCEPTS_SYSTEM_MESSAGES: Readonly<Record<Tier, boolean>> = { haiku: false, sonnet: true, opus: true, fable: true };
const ACCEPTS_EFFORT: Readonly<Record<Tier, boolean>> = { haiku: false, sonnet: true, opus: true, fable: true };

/** Native Haiku 4.5 requests from Claude Code use this budget (with max_tokens 32000). */
export const HAIKU_THINKING_BUDGET = 31999;
/** The API's minimum thinking budget. */
const MIN_THINKING_BUDGET = 1024;

/**
 * Source -> target pairs whose rewrite the API accepted in real sessions (docs/wire-format.md §5.1-5.5,
 * test/fixtures/claude-code/2.1.277/experiment.*, 2.1.278/experiment.route-haiku-*). Route mode only rewrites these;
 * anything else is logged as `rewrite_unverified` and forwarded unchanged.
 */
const VERIFIED_RETARGETS: ReadonlySet<string> = new Set(["sonnet>haiku", "opus>sonnet", "opus>haiku", "haiku>sonnet", "haiku>opus", "sonnet>opus"]);
export const isVerifiedRetarget = (from: Tier, to: Tier): boolean => VERIFIED_RETARGETS.has(`${from}>${to}`);

/**
 * `anthropic-beta` values a target model rejects, removed from the header when a request is retargeted to it (the
 * rest of the header is kept as is). Each row names the evidence.
 */
export const STRIP_BETAS: readonly { readonly to: Tier; readonly prefix: string; readonly evidence: string }[] = [
  {
    to: "haiku",
    prefix: "context-1m-",
    evidence:
      "route acceptance session B1 (opus[1m] -> Haiku): 400 \"The long context beta is not yet available for this subscription.\"; " +
      "interactive-opus1m.main-new-turn fixture; experiment.interactive-opus1m-first-turn-to-haiku",
  },
];

/** The `anthropic-beta` header for a request retargeted to `to`, and the values removed from it. Pure. */
export function retargetBetas(header: string | undefined, to: Tier): { readonly value: string | undefined; readonly stripped: readonly string[] } {
  if (header === undefined) return { value: undefined, stripped: [] };
  const rules = STRIP_BETAS.filter((r) => r.to === to);
  const parts = header.split(",").map((x) => x.trim()).filter(Boolean);
  const stripped = parts.filter((b) => rules.some((r) => b.startsWith(r.prefix)));
  if (stripped.length === 0) return { value: header, stripped: [] };
  return { value: parts.filter((b) => !stripped.includes(b)).join(","), stripped };
}

export interface RewriteOptions {
  readonly from: Tier;
  readonly to: Tier;
  readonly model: string;
  /** Drop `thinking`/`redacted_thinking` blocks generated by another model from the history. */
  readonly dropHistoryThinking?: boolean;
}

export type RewriteResult =
  | { readonly ok: true; readonly body: Buffer; readonly fields: readonly string[] }
  | { readonly ok: false; readonly reason: "not_json" | "no_messages" | "thinking_budget_too_small" };

type Json = Record<string, unknown>;
const isObj = (v: unknown): v is Json => typeof v === "object" && v !== null && !Array.isArray(v);
const blocksOf = (content: unknown): unknown[] => (typeof content === "string" ? [{ type: "text", text: content }] : Array.isArray(content) ? content : []);

/**
 * Folds every role:"system" message into the closest earlier user message (appended, so tool_result blocks stay
 * first), or into the next user message when none precedes it. Deterministic, so a pinned tool loop folds the same
 * history the same way on every request and the rewritten prefix stays cacheable.
 */
function foldSystemMessages(messages: Json[]): { messages: Json[]; folded: number } {
  const out: Json[] = [];
  let pending: unknown[] = [];
  let folded = 0;
  for (const m of messages) {
    if (m["role"] === "system") {
      folded++;
      const target = [...out].reverse().find((x) => x["role"] === "user");
      if (target) target["content"] = [...blocksOf(target["content"]), ...blocksOf(m["content"])];
      else pending.push(...blocksOf(m["content"]));
      continue;
    }
    const copy: Json = { ...m };
    if (pending.length > 0 && copy["role"] === "user") {
      copy["content"] = [...pending, ...blocksOf(copy["content"])];
      pending = [];
    }
    out.push(copy);
  }
  return { messages: out, folded };
}

export function retarget(body: Buffer, opts: RewriteOptions): RewriteResult {
  let b: Json;
  try {
    const parsed: unknown = JSON.parse(body.toString("utf8"));
    if (!isObj(parsed)) return { ok: false, reason: "not_json" };
    b = parsed;
  } catch {
    return { ok: false, reason: "not_json" };
  }
  if (!Array.isArray(b["messages"])) return { ok: false, reason: "no_messages" };
  const fields: string[] = [];

  b["model"] = opts.model;
  fields.push("model");

  const oc = b["output_config"];
  if (!ACCEPTS_EFFORT[opts.to] && isObj(oc) && "effort" in oc) {
    const rest = Object.fromEntries(Object.entries(oc).filter(([k]) => k !== "effort"));
    if (Object.keys(rest).length > 0) b["output_config"] = rest;
    else delete b["output_config"];
    fields.push("output_config.effort");
  }

  const th = b["thinking"];
  if (isObj(th)) {
    const display = th["display"];
    if (STYLE[opts.to] === "budget" && th["type"] === "adaptive") {
      const max = typeof b["max_tokens"] === "number" ? b["max_tokens"] : HAIKU_THINKING_BUDGET + 1;
      const budget = Math.min(HAIKU_THINKING_BUDGET, max - 1);
      if (budget < MIN_THINKING_BUDGET) return { ok: false, reason: "thinking_budget_too_small" };
      b["thinking"] = { type: "enabled", budget_tokens: budget, ...(display !== undefined ? { display } : {}) };
      fields.push("thinking");
    } else if (STYLE[opts.to] === "adaptive" && th["type"] === "enabled") {
      b["thinking"] = { type: "adaptive", ...(display !== undefined ? { display } : {}) };
      fields.push("thinking");
    }
  }

  let messages = (b["messages"] as unknown[]).filter(isObj);
  if (!ACCEPTS_SYSTEM_MESSAGES[opts.to] && messages.some((m) => m["role"] === "system")) {
    const r = foldSystemMessages(messages);
    messages = r.messages;
    fields.push(`messages.system_folded:${r.folded}`);
  }
  if (opts.dropHistoryThinking) {
    let dropped = 0;
    messages = messages.map((m) => {
      if (m["role"] !== "assistant" || !Array.isArray(m["content"])) return m;
      const kept = (m["content"] as unknown[]).filter((c) => !(isObj(c) && (c["type"] === "thinking" || c["type"] === "redacted_thinking")));
      dropped += (m["content"] as unknown[]).length - kept.length;
      return kept.length === (m["content"] as unknown[]).length ? m : { ...m, content: kept };
    });
    if (dropped > 0) fields.push(`messages.thinking_dropped:${dropped}`);
  }
  b["messages"] = messages;

  return { ok: true, body: Buffer.from(JSON.stringify(b)), fields };
}
