// GENERATED by scripts/gen-tested-versions.mjs from test/fixtures/claude-code/. Do not edit; run `npm run gen:versions`.
// Claude Code versions we hold captured, redacted fixtures for.
export const TESTED_CLAUDE_VERSIONS: readonly string[] = ["2.1.277"];
