// Generated by scripts/calibrate/fit.ts from recorded Jev/Laya pairs; do not edit by hand. Parameters only: no text.
import type { LayaModel } from "../config.js";
import type { LayaCalibration } from "./laya-calibration.js";

export const LAYA_CALIBRATIONS: Partial<Record<LayaModel, LayaCalibration>> = {};
